on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: A job to print available space
    steps:
      - uses: actions/checkout@v2
      - name: get avialable space
        id: available-space
        uses: ./
      - run: echo available-space ${{ steps.available-space.outputs.available-space }}
        shell: bash
      - name: never clean
        uses: ./
        with:
          clean-threadshold: 0
          clean: echo "Never execute"
      - name: always clean
        uses: ./
        with:
          clean-threadshold: 1000000000
          clean: echo "Always execute"
